EVENT_EXEC = 1
EVENT_CONNECT = 2
EVENT_MEMFD = 3
EVENT_MPROTECT = 4
EVENT_VM_WRITE = 5


EVENT_NAME_MAP = {
    EVENT_EXEC: "EXECVE",
    EVENT_CONNECT: "NETWORK_CONNECT",
    EVENT_MEMFD: "MEMFD_CREATE",
    EVENT_MPROTECT: "MPROTECT_EXEC",
    EVENT_VM_WRITE: "PROCESS_VM_WRITEV"
}